title: 狼与凤梨田
email: amarokice@outlook.com
description: "Hope you're happy!"
baseurl: ""
url: "https://wolf.snowlyicewolf.club"
# twitter_username:
github_username: AmarokIce

markdown: kramdown

kramdown:
  syntax_highlighter: rouge
gems:
  - jemoji

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
