title: 狼与凤梨田
email: amarokice@outlook.com
description: I'm just a little wolf in this bigger world.

# baseurl: "https://wolf.snowlyicewolf.club"
url: "https://wolf.snowlyicewolf.club"

github_username: AmarokIce

markdown: kramdown

kramdown:
  syntax_highlighter: rouge

gems:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]

permalink: /:year-:month/:title.html

timezone: Asia/Shanghai

category_info:
  以狼观世: 虽然我只是这偌大世界的一只小狼，但小狼也可以用双眼观察世界。
  日常: 随记，突发奇想的内容，以及一些可有可无的记录。
  学习笔记: 记录一些问题的解决方案，或是一些有意思的内容。
  狼癫疯: 大多时候只是因为饿了而感到愤怒然后开始写文章。

freind_links:
  - webname: "墨青的博客"
    name: "墨青BlackCyan"
    webside: "https://blog.blackcyan.top/"
    avatar: "https://avatars.githubusercontent.com/u/117635344"
    info: "别工作了，饮咖啡先!"

  - webname: "KrKrLite 的故事"
    name: "KrKrLite"
    webside: "https://krlite.netlify.app/"
    avatar: "https://avatars.githubusercontent.com/u/68179735"
    info: "人生中总会发生一些事。无论是否值得被回忆、被忘却、被纪念，它们终会在时间的土层之下完成自己的宿命。与其待之埋没于扬尘，不如将它们在此记下。"

  - webname: "锐龙的小窝"
    name: "锐冰龙"
    webside: "https://github.com/SharpIceX"
    avatar: "https://avatars.githubusercontent.com/u/61524717"
    info: "贴贴～"

