title: 狼与凤梨田
email: amarokice@outlook.com
description: I'm just a little wolf in this bigger world.

# baseurl: "https://wolf.snowlyicewolf.club"
url: "https://wolf.snowlyicewolf.club"

github_username: AmarokIce

markdown: kramdown

kramdown:
  syntax_highlighter: rouge

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]

permalink: /:year-:month/:title.html

timezone: Asia/Shanghai
