title: 狼与凤梨田
email: amarokice@outlook.com
description: >
  I never pretend to understand the moon-- she's much bigger than I am.
baseurl: "https://wolf.snowlyicewolf.club"
url: "https://wolf.snowlyicewolf.club"

github_username: AmarokIce

markdown: kramdown

kramdown:
  syntax_highlighter: rouge

gems:
  - jemoji

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]

permalink: /:year-:month/:title.html

timezone: Asia/Shanghai

plugin:
  - jekyll-sitemap
